// <auto-generated />
namespace SmartStore.GoogleMerchantCenter.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class IsTouched : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsTouched));
        
        string IMigrationMetadata.Id
        {
            get { return "201408020941244_IsTouched"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
