// <auto-generated />
namespace SmartStore.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class PrimaryStoreCurrencyMultiStore : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PrimaryStoreCurrencyMultiStore));
        
        string IMigrationMetadata.Id
        {
            get { return "201506261756463_PrimaryStoreCurrencyMultiStore"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
