// <auto-generated />
namespace SmartStore.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Merge5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Merge5));
        
        string IMigrationMetadata.Id
        {
            get { return "201908211821559_Merge5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
