// <auto-generated />
namespace SmartStore.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class V321Resources : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V321Resources));
        
        string IMigrationMetadata.Id
        {
            get { return "201905271110370_V321Resources"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
