// <auto-generated />
namespace SmartStore.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddBlogAndNewsLanguage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddBlogAndNewsLanguage));
        
        string IMigrationMetadata.Id
        {
            get { return "202012051645539_AddBlogAndNewsLanguage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
