// <auto-generated />
namespace SmartStore.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class V420Resources : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V420Resources));
        
        string IMigrationMetadata.Id
        {
            get { return "202112171231491_V420Resources"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
