//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder-Klasse
    // mit einem Tool wie ResGen oder Visual Studio automatisch generiert.
    // Bearbeiten Sie zum Hinzufügen oder Entfernen eines Members die RESX-Datei, und führen Sie dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen das Visual Studio-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GridLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GridLocalization() {
        }
        
        /// <summary>
        ///   Gibt die von dieser Klasse verwendete zwischengespeicherte ResourceManager-Instanz zurück.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GridLocalization", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenlookups, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add new record ähnelt.
        /// </summary>
        internal static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel changes ähnelt.
        /// </summary>
        internal static string CancelChanges {
            get {
                return ResourceManager.GetString("CancelChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure you want to delete this record? ähnelt.
        /// </summary>
        internal static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Displaying items {0} - {1} of {2} ähnelt.
        /// </summary>
        internal static string DisplayingItems {
            get {
                return ResourceManager.GetString("DisplayingItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter ähnelt.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die And ähnelt.
        /// </summary>
        internal static string FilterAnd {
            get {
                return ResourceManager.GetString("FilterAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die is false ähnelt.
        /// </summary>
        internal static string FilterBoolIsFalse {
            get {
                return ResourceManager.GetString("FilterBoolIsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die is true ähnelt.
        /// </summary>
        internal static string FilterBoolIsTrue {
            get {
                return ResourceManager.GetString("FilterBoolIsTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear Filter ähnelt.
        /// </summary>
        internal static string FilterClear {
            get {
                return ResourceManager.GetString("FilterClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is equal to ähnelt.
        /// </summary>
        internal static string FilterDateEq {
            get {
                return ResourceManager.GetString("FilterDateEq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is after or equal to ähnelt.
        /// </summary>
        internal static string FilterDateGe {
            get {
                return ResourceManager.GetString("FilterDateGe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is after ähnelt.
        /// </summary>
        internal static string FilterDateGt {
            get {
                return ResourceManager.GetString("FilterDateGt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is before or equal to ähnelt.
        /// </summary>
        internal static string FilterDateLe {
            get {
                return ResourceManager.GetString("FilterDateLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is before ähnelt.
        /// </summary>
        internal static string FilterDateLt {
            get {
                return ResourceManager.GetString("FilterDateLt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is not equal to ähnelt.
        /// </summary>
        internal static string FilterDateNe {
            get {
                return ResourceManager.GetString("FilterDateNe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is equal to ähnelt.
        /// </summary>
        internal static string FilterEnumEq {
            get {
                return ResourceManager.GetString("FilterEnumEq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is not equal to ähnelt.
        /// </summary>
        internal static string FilterEnumNe {
            get {
                return ResourceManager.GetString("FilterEnumNe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is equal to ähnelt.
        /// </summary>
        internal static string FilterForeignKeyEq {
            get {
                return ResourceManager.GetString("FilterForeignKeyEq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is not equal to ähnelt.
        /// </summary>
        internal static string FilterForeignKeyNe {
            get {
                return ResourceManager.GetString("FilterForeignKeyNe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is equal to ähnelt.
        /// </summary>
        internal static string FilterNumberEq {
            get {
                return ResourceManager.GetString("FilterNumberEq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is greater than or equal to ähnelt.
        /// </summary>
        internal static string FilterNumberGe {
            get {
                return ResourceManager.GetString("FilterNumberGe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is greater than ähnelt.
        /// </summary>
        internal static string FilterNumberGt {
            get {
                return ResourceManager.GetString("FilterNumberGt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is less than or equal to ähnelt.
        /// </summary>
        internal static string FilterNumberLe {
            get {
                return ResourceManager.GetString("FilterNumberLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is less than ähnelt.
        /// </summary>
        internal static string FilterNumberLt {
            get {
                return ResourceManager.GetString("FilterNumberLt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is not equal to ähnelt.
        /// </summary>
        internal static string FilterNumberNe {
            get {
                return ResourceManager.GetString("FilterNumberNe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Or ähnelt.
        /// </summary>
        internal static string FilterOr {
            get {
                return ResourceManager.GetString("FilterOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die -Select value- ähnelt.
        /// </summary>
        internal static string FilterSelectValue {
            get {
                return ResourceManager.GetString("FilterSelectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show rows with value that ähnelt.
        /// </summary>
        internal static string FilterShowRows {
            get {
                return ResourceManager.GetString("FilterShowRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ends with ähnelt.
        /// </summary>
        internal static string FilterStringEndsWith {
            get {
                return ResourceManager.GetString("FilterStringEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is equal to ähnelt.
        /// </summary>
        internal static string FilterStringEq {
            get {
                return ResourceManager.GetString("FilterStringEq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is not equal to ähnelt.
        /// </summary>
        internal static string FilterStringNe {
            get {
                return ResourceManager.GetString("FilterStringNe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Does not contain ähnelt.
        /// </summary>
        internal static string FilterStringNotSubstringOf {
            get {
                return ResourceManager.GetString("FilterStringNotSubstringOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starts with ähnelt.
        /// </summary>
        internal static string FilterStringStartsWith {
            get {
                return ResourceManager.GetString("FilterStringStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contains ähnelt.
        /// </summary>
        internal static string FilterStringSubstringOf {
            get {
                return ResourceManager.GetString("FilterStringSubstringOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drag a column header and drop it here to group by that column ähnelt.
        /// </summary>
        internal static string GroupHint {
            get {
                return ResourceManager.GetString("GroupHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert ähnelt.
        /// </summary>
        internal static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No records to display. ähnelt.
        /// </summary>
        internal static string NoRecords {
            get {
                return ResourceManager.GetString("NoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Page  ähnelt.
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die of {0} ähnelt.
        /// </summary>
        internal static string PageOf {
            get {
                return ResourceManager.GetString("PageOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refresh ähnelt.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save changes ähnelt.
        /// </summary>
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select ähnelt.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die sorted ascending ähnelt.
        /// </summary>
        internal static string SortedAsc {
            get {
                return ResourceManager.GetString("SortedAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die sorted descending ähnelt.
        /// </summary>
        internal static string SortedDesc {
            get {
                return ResourceManager.GetString("SortedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ungroup ähnelt.
        /// </summary>
        internal static string UnGroup {
            get {
                return ResourceManager.GetString("UnGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update ähnelt.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
