//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18052
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartStore.Plugin.Widgets.TrustedShopsCustomerReviews.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.trustedshops.com:443/ts/services/TsRating")]
        public string SmartStore_Plugin_Widgets_TrustedShopsCustomerReviews_com_trustedshops_www_TSRatingService {
            get {
                return ((string)(this["SmartStore_Plugin_Widgets_TrustedShopsCustomerReviews_com_trustedshops_www_TSRati" +
                    "ngService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://qa.trustedshops.com:443/ts/services/TsRating")]
        public string SmartStore_Plugin_Widgets_TrustedShopsCustomerReviews_com_trustedshops_qa_TSRatingService {
            get {
                return ((string)(this["SmartStore_Plugin_Widgets_TrustedShopsCustomerReviews_com_trustedshops_qa_TSRatin" +
                    "gService"]));
            }
        }
    }
}
