
IF EXISTS (SELECT 1 FROM [MessageTemplate] WHERE [Name] = 'Blog.BlogComment')
BEGIN
	UPDATE [MessageTemplate] SET [Body] = '<style type="text/css">address, blockquote, center, del, dir, div, dl, fieldset, form, h1, h2, h3, h4, h5, h6, hr, ins, isindex, menu, noframes, noscript, ol, p, pre, table{ margin:0px; } body, td, p{ font-size: 13px;font-family: ''Segoe UI'', Tahoma, Arial, Helvetica, sans-serif; line-height: 18px; color: #163764; } body{ background:#efefef; } p{ margin-top: 0px; margin-bottom: 10px; } img{ border:0px; } th{ font-weight:bold; color: #ffffff; padding: 5px 0 5px 0; } ul{ list-style-type: square; } li{ line-height: normal; margin-bottom: 5px; } .template-body { width:720px; padding: 10px; border: 1px solid #ccc; } .attr-caption { font-weight: bold; text-align:right; } .attr-value { text-align:right; min-width:158px; width:160px; } .legal-infos, .legal-infos p { font-size:11px; color: #aaa} .supplier-identification, .supplier-identification td { color: #646464; font-size: 11px } .supplier-identification { width:100%;border-top: 1px solid #ccc; border-bottom: 1px solid #ccc }</style><center><table border="0" cellpadding="0" cellspacing="0" align="center" bgcolor="#ffffff" class="template-body"><tbody><tr><td><p><a href=" % Store.URL % ">%Store.Name%</a>&nbsp;</p> <p>Ein neuer Kommentar wurde zu dem Blog-Eintrag&nbsp;" % BlogComment.BlogPostTitle % " abgegeben.<br /><br /></p></td></tr></tbody></table></center>'
	WHERE [Name] = 'Blog.BlogComment'
END
GO

IF EXISTS (SELECT 1 FROM [MessageTemplate] WHERE [Name] = 'Customer.BackInStock')
BEGIN
	UPDATE [MessageTemplate] SET [Body] = '<style type="text/css">address, blockquote, center, del, dir, div, dl, fieldset, form, h1, h2, h3, h4, h5, h6, hr, ins, isindex, menu, noframes, noscript, ol, p, pre, table{ margin:0px; } body, td, p{ font-size: 13px;font-family: ''Segoe UI'', Tahoma, Arial, Helvetica, sans-serif; line-height: 18px; color: #163764; } body{ background:#efefef; } p{ margin-top: 0px; margin-bottom: 10px; } img{ border:0px; } th{ font-weight:bold; color: #ffffff; padding: 5px 0 5px 0; } ul{ list-style-type: square; } li{ line-height: normal; margin-bottom: 5px; } .template-body { width:720px; padding: 10px; border: 1px solid #ccc; } .attr-caption { font-weight: bold; text-align:right; } .attr-value { text-align:right; min-width:158px; width:160px; } .legal-infos, .legal-infos p { font-size:11px; color: #aaa} .supplier-identification, .supplier-identification td { color: #646464; font-size: 11px } .supplier-identification { width:100%;border-top: 1px solid #ccc; border-bottom: 1px solid #ccc }</style><center><table border="0" cellpadding="0" cellspacing="0" align="center" bgcolor="#ffffff" class="template-body"><tbody><tr><td><p><a href="%Store.URL%">%Store.Name%</a>&nbsp;</p> <p></p> <p>Hallo&nbsp;%Customer.FullName%,&nbsp;</p> <p></p> <p>der Artikel&nbsp;"%BackInStockSubscription.ProductName%" ist wieder verf&uuml;gbar.</p> <p></p> <p>Mit freundlichen Gr&uuml;&szlig;en,</p> <p></p> <p>Ihr Shop-Team</p> <p><br /><br /></p></td></tr></tbody></table></center>'
	WHERE [Name] = 'Customer.BackInStock'
END
GO

IF EXISTS (SELECT 1 FROM [MessageTemplate] WHERE [Name] = 'Customer.EmailValidationMessage')
BEGIN
	UPDATE [MessageTemplate] SET [Body] = '<style type="text/css">address, blockquote, center, del, dir, div, dl, fieldset, form, h1, h2, h3, h4, h5, h6, hr, ins, isindex, menu, noframes, noscript, ol, p, pre, table{ margin:0px; } body, td, p{ font-size: 13px;font-family: ''Segoe UI'', Tahoma, Arial, Helvetica, sans-serif; line-height: 18px; color: #163764; } body{ background:#efefef; } p{ margin-top: 0px; margin-bottom: 10px; } img{ border:0px; } th{ font-weight:bold; color: #ffffff; padding: 5px 0 5px 0; } ul{ list-style-type: square; } li{ line-height: normal; margin-bottom: 5px; } .template-body { width:720px; padding: 10px; border: 1px solid #ccc; } .attr-caption { font-weight: bold; text-align:right; } .attr-value { text-align:right; min-width:158px; width:160px; } .legal-infos, .legal-infos p { font-size:11px; color: #aaa} .supplier-identification, .supplier-identification td { color: #646464; font-size: 11px } .supplier-identification { width:100%;border-top: 1px solid #ccc; border-bottom: 1px solid #ccc }</style><center><table border="0" cellpadding="0" cellspacing="0" align="center" bgcolor="#ffffff" class="template-body"><tbody><tr><td><p><a href="%Store.URL%">%Store.Name%</a>&nbsp;<br /><br /></p> <p>Bitte best&auml;tigen Sie Ihre Registrierung mit einem Klick auf diesen <a href="%Customer.AccountActivationURL%">Link</a>.</p> <p></p> <p><br />Ihr Shop-Team</p></td></tr></tbody></table></center>'
	WHERE [Name] = 'Customer.EmailValidationMessage'
END
GO

IF EXISTS (SELECT 1 FROM [MessageTemplate] WHERE [Name] = 'Customer.NewPM')
BEGIN
	UPDATE [MessageTemplate] SET [Body] = '<style type="text/css">address, blockquote, center, del, dir, div, dl, fieldset, form, h1, h2, h3, h4, h5, h6, hr, ins, isindex, menu, noframes, noscript, ol, p, pre, table{ margin:0px; } body, td, p{ font-size: 13px;font-family: ''Segoe UI'', Tahoma, Arial, Helvetica, sans-serif; line-height: 18px; color: #163764; } body{ background:#efefef; } p{ margin-top: 0px; margin-bottom: 10px; } img{ border:0px; } th{ font-weight:bold; color: #ffffff; padding: 5px 0 5px 0; } ul{ list-style-type: square; } li{ line-height: normal; margin-bottom: 5px; } .template-body { width:720px; padding: 10px; border: 1px solid #ccc; } .attr-caption { font-weight: bold; text-align:right; } .attr-value { text-align:right; min-width:158px; width:160px; } .legal-infos, .legal-infos p { font-size:11px; color: #aaa} .supplier-identification, .supplier-identification td { color: #646464; font-size: 11px } .supplier-identification { width:100%;border-top: 1px solid #ccc; border-bottom: 1px solid #ccc }</style><center><table border="0" cellpadding="0" cellspacing="0" align="center" bgcolor="#ffffff" class="template-body"><tbody><tr><td><p><a href="%Store.URL%">%Store.Name%</a>&nbsp;<br /><br />Sie haben eine neue pers&ouml;nliche Nachricht erhalten.</p></td></tr></tbody></table></center>'
	WHERE [Name] = 'Customer.NewPM'
END
GO

IF EXISTS (SELECT 1 FROM [MessageTemplate] WHERE [Name] = 'Customer.PasswordRecovery')
BEGIN
	UPDATE [MessageTemplate] SET [Body] = '<style type="text/css">address, blockquote, center, del, dir, div, dl, fieldset, form, h1, h2, h3, h4, h5, h6, hr, ins, isindex, menu, noframes, noscript, ol, p, pre, table{ margin:0px; } body, td, p{ font-size: 13px;font-family: ''Segoe UI'', Tahoma, Arial, Helvetica, sans-serif; line-height: 18px; color: #163764; } body{ background:#efefef; } p{ margin-top: 0px; margin-bottom: 10px; } img{ border:0px; } th{ font-weight:bold; color: #ffffff; padding: 5px 0 5px 0; } ul{ list-style-type: square; } li{ line-height: normal; margin-bottom: 5px; } .template-body { width:720px; padding: 10px; border: 1px solid #ccc; } .attr-caption { font-weight: bold; text-align:right; } .attr-value { text-align:right; min-width:158px; width:160px; } .legal-infos, .legal-infos p { font-size:11px; color: #aaa} .supplier-identification, .supplier-identification td { color: #646464; font-size: 11px } .supplier-identification { width:100%;border-top: 1px solid #ccc; border-bottom: 1px solid #ccc }</style><center><table border="0" cellpadding="0" cellspacing="0" align="center" bgcolor="#ffffff" class="template-body"><tbody><tr><td><p><a href="%Store.URL%">%Store.Name%</a>&nbsp;</p> <p>Um Ihr Kennwort zur&uuml;ckzusetzen klicken Sie bitte <a href="%Customer.PasswordRecoveryURL%">hier</a>.</p> <p></p> <p>Mit freundlichen Gr&uuml;&szlig;en,</p> <p></p> <p>Ihr Shop-Team</p> <p><br /><br /></p></td></tr></tbody></table></center>'
	WHERE [Name] = 'Customer.PasswordRecovery'
END
GO

IF EXISTS (SELECT 1 FROM [MessageTemplate] WHERE [Name] = 'Customer.WelcomeMessage')
BEGIN
	UPDATE [MessageTemplate] SET [Body] = '<style type="text/css">address, blockquote, center, del, dir, div, dl, fieldset, form, h1, h2, h3, h4, h5, h6, hr, ins, isindex, menu, noframes, noscript, ol, p, pre, table{ margin:0px; } body, td, p{ font-size: 13px;font-family: ''Segoe UI'', Tahoma, Arial, Helvetica, sans-serif; line-height: 18px; color: #163764; } body{ background:#efefef; } p{ margin-top: 0px; margin-bottom: 10px; } img{ border:0px; } th{ font-weight:bold; color: #ffffff; padding: 5px 0 5px 0; } ul{ list-style-type: square; } li{ line-height: normal; margin-bottom: 5px; } .template-body { width:720px; padding: 10px; border: 1px solid #ccc; } .attr-caption { font-weight: bold; text-align:right; } .attr-value { text-align:right; min-width:158px; width:160px; } .legal-infos, .legal-infos p { font-size:11px; color: #aaa} .supplier-identification, .supplier-identification td { color: #646464; font-size: 11px } .supplier-identification { width:100%;border-top: 1px solid #ccc; border-bottom: 1px solid #ccc }</style><center><table border="0" cellpadding="0" cellspacing="0" align="center" bgcolor="#ffffff" class="template-body"><tbody><tr><td><p>Herzlich Willkommen in unserem Online-Shop <a href="%Store.URL%">%Store.Name%</a>!</p> <p>St&ouml;bern Sie in Warengruppen und Produkte, Lesen Sie im Blog und tauschen Sie Ihre Meinung im Forum aus.</p> <p>Nehmen Sie auch an unseren Umfragen teil!</p> <p></p> <p>Mit freundlichen Gr&uuml;&szlig;en,</p> <p></p> <p>Ihr Shop-Team</p></td></tr></tbody></table></center>'
	WHERE [Name] = 'Customer.WelcomeMessage'
END
GO

IF EXISTS (SELECT 1 FROM [MessageTemplate] WHERE [Name] = 'Forums.NewForumPost')
BEGIN
	UPDATE [MessageTemplate] SET [Body] = '<style type="text/css">address, blockquote, center, del, dir, div, dl, fieldset, form, h1, h2, h3, h4, h5, h6, hr, ins, isindex, menu, noframes, noscript, ol, p, pre, table{ margin:0px; } body, td, p{ font-size: 13px;font-family: ''Segoe UI'', Tahoma, Arial, Helvetica, sans-serif; line-height: 18px; color: #163764; } body{ background:#efefef; } p{ margin-top: 0px; margin-bottom: 10px; } img{ border:0px; } th{ font-weight:bold; color: #ffffff; padding: 5px 0 5px 0; } ul{ list-style-type: square; } li{ line-height: normal; margin-bottom: 5px; } .template-body { width:720px; padding: 10px; border: 1px solid #ccc; } .attr-caption { font-weight: bold; text-align:right; } .attr-value { text-align:right; min-width:158px; width:160px; } .legal-infos, .legal-infos p { font-size:11px; color: #aaa} .supplier-identification, .supplier-identification td { color: #646464; font-size: 11px } .supplier-identification { width:100%;border-top: 1px solid #ccc; border-bottom: 1px solid #ccc }</style><center><table border="0" cellpadding="0" cellspacing="0" align="center" bgcolor="#ffffff" class="template-body"><tbody><tr><td><p><a href="%Store.URL%">%Store.Name%</a>&nbsp;</p> <p></p> <p>Ein neuer Beitrag wurde in&nbsp;<a href="%Forums.TopicURL%">"%Forums.TopicName%"</a>&nbsp;im Forum&nbsp;<a href="%Forums.ForumURL%">"%Forums.ForumName%"</a>&nbsp;erstellt.</p> <p>Klicken Sie <a href="%Forums.TopicURL%">hier</a> f&uuml;r weitere Informationen.</p> <p>Autor des Beitrags:&nbsp;%Forums.PostAuthor%<br />Inhalt des Beitrags: %Forums.PostBody%</p> <p></p> <p>Mit freundlichen Gr&uuml;&szlig;en,</p> <p></p> <p>Ihr Shop-Team</p></td></tr></tbody></table></center>'
	WHERE [Name] = 'Forums.NewForumPost'
END
GO

IF EXISTS (SELECT 1 FROM [MessageTemplate] WHERE [Name] = 'Forums.NewForumTopic')
BEGIN
	UPDATE [MessageTemplate] SET [Body] = '<style type="text/css">address, blockquote, center, del, dir, div, dl, fieldset, form, h1, h2, h3, h4, h5, h6, hr, ins, isindex, menu, noframes, noscript, ol, p, pre, table{ margin:0px; } body, td, p{ font-size: 13px;font-family: ''Segoe UI'', Tahoma, Arial, Helvetica, sans-serif; line-height: 18px; color: #163764; } body{ background:#efefef; } p{ margin-top: 0px; margin-bottom: 10px; } img{ border:0px; } th{ font-weight:bold; color: #ffffff; padding: 5px 0 5px 0; } ul{ list-style-type: square; } li{ line-height: normal; margin-bottom: 5px; } .template-body { width:720px; padding: 10px; border: 1px solid #ccc; } .attr-caption { font-weight: bold; text-align:right; } .attr-value { text-align:right; min-width:158px; width:160px; } .legal-infos, .legal-infos p { font-size:11px; color: #aaa} .supplier-identification, .supplier-identification td { color: #646464; font-size: 11px } .supplier-identification { width:100%;border-top: 1px solid #ccc; border-bottom: 1px solid #ccc }</style><center><table border="0" cellpadding="0" cellspacing="0" align="center" bgcolor="#ffffff" class="template-body"><tbody><tr><td><p><a href="%Store.URL%">%Store.Name%</a>&nbsp;</p> <p></p> <p>Ein neuer Beitrag <a href="%Forums.TopicURL%">"%Forums.TopicName%"</a>&nbsp;wurde im Forum &nbsp;<a href="%Forums.ForumURL%">"%Forums.ForumName%"</a>&nbsp;erstellt.</p> <p>Klicken Sie <a href="%Forums.TopicURL%">hier</a> f&uuml;r weitere Informationen.</p> <p></p> <p>Mit freundlichen Gr&uuml;&szlig;en,</p> <p></p> <p>Ihr Shop-Team</p></td></tr></tbody></table></center>'
	WHERE [Name] = 'Forums.NewForumTopic'
END
GO

IF EXISTS (SELECT 1 FROM [MessageTemplate] WHERE [Name] = 'GiftCard.Notification')
BEGIN
	UPDATE [MessageTemplate] SET [Body] = '<style type="text/css">address, blockquote, center, del, dir, div, dl, fieldset, form, h1, h2, h3, h4, h5, h6, hr, ins, isindex, menu, noframes, noscript, ol, p, pre, table{ margin:0px; } body, td, p{ font-size: 13px;font-family: ''Segoe UI'', Tahoma, Arial, Helvetica, sans-serif; line-height: 18px; color: #163764; } body{ background:#efefef; } p{ margin-top: 0px; margin-bottom: 10px; } img{ border:0px; } th{ font-weight:bold; color: #ffffff; padding: 5px 0 5px 0; } ul{ list-style-type: square; } li{ line-height: normal; margin-bottom: 5px; } .template-body { width:720px; padding: 10px; border: 1px solid #ccc; } .attr-caption { font-weight: bold; text-align:right; } .attr-value { text-align:right; min-width:158px; width:160px; } .legal-infos, .legal-infos p { font-size:11px; color: #aaa} .supplier-identification, .supplier-identification td { color: #646464; font-size: 11px } .supplier-identification { width:100%;border-top: 1px solid #ccc; border-bottom: 1px solid #ccc }</style><center><table border="0" cellpadding="0" cellspacing="0" align="center" bgcolor="#ffffff" class="template-body"><tbody><tr><td><p>Hallo&nbsp;%GiftCard.RecipientName%,</p> <p></p> <p>Sie haben einen Geschenkgutschein in H&ouml;he von %GiftCard.Amount%&nbsp;f&uuml;r den Online-Shop&nbsp;%Store.Name% erhalten</p> <p>Ihr Gutscheincode lautet&nbsp;%GiftCard.CouponCode%</p> <p>Diese Nachricht wurde mit gesendet:</p> <p>%GiftCard.Message%</p> <p></p> <p>Mit freundlichen Gr&uuml;&szlig;en,</p> <p></p> <p>Ihr&nbsp;%Store.Name% - Team</p></td></tr></tbody></table></center>'
	WHERE [Name] = 'GiftCard.Notification'
END
GO

IF EXISTS (SELECT 1 FROM [MessageTemplate] WHERE [Name] = 'NewCustomer.Notification')
BEGIN
	UPDATE [MessageTemplate] SET [Body] = '<style type="text/css">address, blockquote, center, del, dir, div, dl, fieldset, form, h1, h2, h3, h4, h5, h6, hr, ins, isindex, menu, noframes, noscript, ol, p, pre, table{ margin:0px; } body, td, p{ font-size: 13px;font-family: ''Segoe UI'', Tahoma, Arial, Helvetica, sans-serif; line-height: 18px; color: #163764; } body{ background:#efefef; } p{ margin-top: 0px; margin-bottom: 10px; } img{ border:0px; } th{ font-weight:bold; color: #ffffff; padding: 5px 0 5px 0; } ul{ list-style-type: square; } li{ line-height: normal; margin-bottom: 5px; } .template-body { width:720px; padding: 10px; border: 1px solid #ccc; } .attr-caption { font-weight: bold; text-align:right; } .attr-value { text-align:right; min-width:158px; width:160px; } .legal-infos, .legal-infos p { font-size:11px; color: #aaa} .supplier-identification, .supplier-identification td { color: #646464; font-size: 11px } .supplier-identification { width:100%;border-top: 1px solid #ccc; border-bottom: 1px solid #ccc }</style><center><table border="0" cellpadding="0" cellspacing="0" align="center" bgcolor="#ffffff" class="template-body"><tbody><tr><td><p><a href="%Store.URL%">%Store.Name%</a>&nbsp;</p> <p>Ein neuer Kunde hat sich registriert:<br /><br />Name: %Customer.FullName%<br />E-Mail: %Customer.Email%</p></td></tr></tbody></table></center>'
	WHERE [Name] = 'NewCustomer.Notification'
END
GO

IF EXISTS (SELECT 1 FROM [MessageTemplate] WHERE [Name] = 'NewReturnRequest.StoreOwnerNotification')
BEGIN
	UPDATE [MessageTemplate] SET [Body] = '<style type="text/css">address, blockquote, center, del, dir, div, dl, fieldset, form, h1, h2, h3, h4, h5, h6, hr, ins, isindex, menu, noframes, noscript, ol, p, pre, table{ margin:0px; } body, td, p{ font-size: 13px;font-family: ''Segoe UI'', Tahoma, Arial, Helvetica, sans-serif; line-height: 18px; color: #163764; } body{ background:#efefef; } p{ margin-top: 0px; margin-bottom: 10px; } img{ border:0px; } th{ font-weight:bold; color: #ffffff; padding: 5px 0 5px 0; } ul{ list-style-type: square; } li{ line-height: normal; margin-bottom: 5px; } .template-body { width:720px; padding: 10px; border: 1px solid #ccc; } .attr-caption { font-weight: bold; text-align:right; } .attr-value { text-align:right; min-width:158px; width:160px; } .legal-infos, .legal-infos p { font-size:11px; color: #aaa} .supplier-identification, .supplier-identification td { color: #646464; font-size: 11px } .supplier-identification { width:100%;border-top: 1px solid #ccc; border-bottom: 1px solid #ccc }</style><center><table border="0" cellpadding="0" cellspacing="0" align="center" bgcolor="#ffffff" class="template-body"><tbody><tr><td><p><a href="%Store.URL%">%Store.Name%</a>&nbsp;</p> <p>%Customer.FullName% hat eine R&uuml;ckgabe-Anforderung geschickt.&nbsp;</p> <p>Anforderungs-ID: %ReturnRequest.ID%<br />Artikel: %ReturnRequest.Product.Quantity% x %ReturnRequest.Product.Name%<br />R&uuml;ckgabegrund: %ReturnRequest.Reason%<br />Gew&uuml;nschte Aktion: %ReturnRequest.RequestedAction%<br />Nachricht vom Kunden:<br />%ReturnRequest.CustomerComment%</p></td></tr></tbody></table></center>'
	WHERE [Name] = 'NewReturnRequest.StoreOwnerNotification'
END
GO

IF EXISTS (SELECT 1 FROM [MessageTemplate] WHERE [Name] = 'News.NewsComment')
BEGIN
	UPDATE [MessageTemplate] SET [Body] = '<style type="text/css">address, blockquote, center, del, dir, div, dl, fieldset, form, h1, h2, h3, h4, h5, h6, hr, ins, isindex, menu, noframes, noscript, ol, p, pre, table{ margin:0px; } body, td, p{ font-size: 13px;font-family: ''Segoe UI'', Tahoma, Arial, Helvetica, sans-serif; line-height: 18px; color: #163764; } body{ background:#efefef; } p{ margin-top: 0px; margin-bottom: 10px; } img{ border:0px; } th{ font-weight:bold; color: #ffffff; padding: 5px 0 5px 0; } ul{ list-style-type: square; } li{ line-height: normal; margin-bottom: 5px; } .template-body { width:720px; padding: 10px; border: 1px solid #ccc; } .attr-caption { font-weight: bold; text-align:right; } .attr-value { text-align:right; min-width:158px; width:160px; } .legal-infos, .legal-infos p { font-size:11px; color: #aaa} .supplier-identification, .supplier-identification td { color: #646464; font-size: 11px } .supplier-identification { width:100%;border-top: 1px solid #ccc; border-bottom: 1px solid #ccc }</style><center><table border="0" cellpadding="0" cellspacing="0" align="center" bgcolor="#ffffff" class="template-body"><tbody><tr><td><p><a href="%Store.URL%">%Store.Name%</a>&nbsp;</p> <p>Zu der News "%NewsComment.NewsTitle%" wurde ein neuer Kommentar eingestellt.</p></td></tr></tbody></table></center>'
	WHERE [Name] = 'News.NewsComment'
END
GO

IF EXISTS (SELECT 1 FROM [MessageTemplate] WHERE [Name] = 'NewsLetterSubscription.ActivationMessage')
BEGIN
	UPDATE [MessageTemplate] SET [Body] = '<style type="text/css">address, blockquote, center, del, dir, div, dl, fieldset, form, h1, h2, h3, h4, h5, h6, hr, ins, isindex, menu, noframes, noscript, ol, p, pre, table{ margin:0px; } body, td, p{ font-size: 13px;font-family: ''Segoe UI'', Tahoma, Arial, Helvetica, sans-serif; line-height: 18px; color: #163764; } body{ background:#efefef; } p{ margin-top: 0px; margin-bottom: 10px; } img{ border:0px; } th{ font-weight:bold; color: #ffffff; padding: 5px 0 5px 0; } ul{ list-style-type: square; } li{ line-height: normal; margin-bottom: 5px; } .template-body { width:720px; padding: 10px; border: 1px solid #ccc; } .attr-caption { font-weight: bold; text-align:right; } .attr-value { text-align:right; min-width:158px; width:160px; } .legal-infos, .legal-infos p { font-size:11px; color: #aaa} .supplier-identification, .supplier-identification td { color: #646464; font-size: 11px } .supplier-identification { width:100%;border-top: 1px solid #ccc; border-bottom: 1px solid #ccc }</style><center><table border="0" cellpadding="0" cellspacing="0" align="center" bgcolor="#ffffff" class="template-body"><tbody><tr><td><p><a href="%NewsLetterSubscription.ActivationUrl%">Klicken Sie hier, um Ihre Newsletter-Registrierung zu bestätigen.</a></p> <p>Sollten Sie diese E-Mail f&auml;lschlich erhalten haben, l&ouml;schen Sie bitte diese E-Mail.</p> <p></p> <p>Ihr&nbsp;%Store.Name% - Team</p></td></tr></tbody></table></center>'
	WHERE [Name] = 'NewsLetterSubscription.ActivationMessage'
END
GO

IF EXISTS (SELECT 1 FROM [MessageTemplate] WHERE [Name] = 'NewsLetterSubscription.DeactivationMessage')
BEGIN
	UPDATE [MessageTemplate] SET [Body] = '<style type="text/css">address, blockquote, center, del, dir, div, dl, fieldset, form, h1, h2, h3, h4, h5, h6, hr, ins, isindex, menu, noframes, noscript, ol, p, pre, table{ margin:0px; } body, td, p{ font-size: 13px;font-family: ''Segoe UI'', Tahoma, Arial, Helvetica, sans-serif; line-height: 18px; color: #163764; } body{ background:#efefef; } p{ margin-top: 0px; margin-bottom: 10px; } img{ border:0px; } th{ font-weight:bold; color: #ffffff; padding: 5px 0 5px 0; } ul{ list-style-type: square; } li{ line-height: normal; margin-bottom: 5px; } .template-body { width:720px; padding: 10px; border: 1px solid #ccc; } .attr-caption { font-weight: bold; text-align:right; } .attr-value { text-align:right; min-width:158px; width:160px; } .legal-infos, .legal-infos p { font-size:11px; color: #aaa} .supplier-identification, .supplier-identification td { color: #646464; font-size: 11px } .supplier-identification { width:100%;border-top: 1px solid #ccc; border-bottom: 1px solid #ccc }</style><center><table border="0" cellpadding="0" cellspacing="0" align="center" bgcolor="#ffffff" class="template-body"><tbody><tr><td><p><a href="%NewsLetterSubscription.DeactivationUrl%">Klicken Sie hier, um Ihre Newsletter-Registrierung zu stornieren.</a></p> <p>Sollten Sie diese E-Mail f&auml;lschlich erhalten haben, l&ouml;schen Sie bitte diese E-Mail.</p> <p></p> <p>Ihr&nbsp;%Store.Name% - Team</p></td></tr></tbody></table></center>'
	WHERE [Name] = 'NewsLetterSubscription.DeactivationMessage'
END
GO

IF EXISTS (SELECT 1 FROM [MessageTemplate] WHERE [Name] = 'NewVATSubmitted.StoreOwnerNotification')
BEGIN
	UPDATE [MessageTemplate] SET [Body] = '<style type="text/css">address, blockquote, center, del, dir, div, dl, fieldset, form, h1, h2, h3, h4, h5, h6, hr, ins, isindex, menu, noframes, noscript, ol, p, pre, table{ margin:0px; } body, td, p{ font-size: 13px;font-family: ''Segoe UI'', Tahoma, Arial, Helvetica, sans-serif; line-height: 18px; color: #163764; } body{ background:#efefef; } p{ margin-top: 0px; margin-bottom: 10px; } img{ border:0px; } th{ font-weight:bold; color: #ffffff; padding: 5px 0 5px 0; } ul{ list-style-type: square; } li{ line-height: normal; margin-bottom: 5px; } .template-body { width:720px; padding: 10px; border: 1px solid #ccc; } .attr-caption { font-weight: bold; text-align:right; } .attr-value { text-align:right; min-width:158px; width:160px; } .legal-infos, .legal-infos p { font-size:11px; color: #aaa} .supplier-identification, .supplier-identification td { color: #646464; font-size: 11px } .supplier-identification { width:100%;border-top: 1px solid #ccc; border-bottom: 1px solid #ccc }</style><center><table border="0" cellpadding="0" cellspacing="0" align="center" bgcolor="#ffffff" class="template-body"><tbody><tr><td><p><a href="%Store.URL%">%Store.Name%</a>&nbsp;<br /><br />%Customer.FullName% (%Customer.Email%) hat eine neue Umsatzsteuer-ID &uuml;bermittelt:</p> <p><br />Umsatzsteuer-ID: %Customer.VatNumber%<br />Status: %Customer.VatNumberStatus%<br />&Uuml;bermittelt von: %VatValidationResult.Name% -&nbsp;%VatValidationResult.Address%</p></td></tr></tbody></table></center>'
	WHERE [Name] = 'NewVATSubmitted.StoreOwnerNotification'
END
GO

IF EXISTS (SELECT 1 FROM [MessageTemplate] WHERE [Name] = 'OrderCancelled.CustomerNotification')
BEGIN
	UPDATE [MessageTemplate] SET [Body] = '<style type="text/css">address, blockquote, center, del, dir, div, dl, fieldset, form, h1, h2, h3, h4, h5, h6, hr, ins, isindex, menu, noframes, noscript, ol, p, pre, table{ margin:0px; } body, td, p{ font-size: 13px;font-family: ''Segoe UI'', Tahoma, Arial, Helvetica, sans-serif; line-height: 18px; color: #163764; } body{ background:#efefef; } p{ margin-top: 0px; margin-bottom: 10px; } img{ border:0px; } th{ font-weight:bold; color: #ffffff; padding: 5px 0 5px 0; } ul{ list-style-type: square; } li{ line-height: normal; margin-bottom: 5px; } .template-body { width:720px; padding: 10px; border: 1px solid #ccc; } .attr-caption { font-weight: bold; text-align:right; } .attr-value { text-align:right; min-width:158px; width:160px; } .legal-infos, .legal-infos p { font-size:11px; color: #aaa} .supplier-identification, .supplier-identification td { color: #646464; font-size: 11px } .supplier-identification { width:100%;border-top: 1px solid #ccc; border-bottom: 1px solid #ccc }</style><center><table border="0" cellpadding="0" cellspacing="0" align="center" bgcolor="#ffffff" class="template-body"><tbody><tr><td><p><a href="%Store.URL%">%Store.Name%</a></p> <p>Hallo %Order.CustomerFullName%,&nbsp;</p> <p>Ihr Auftrag wurde storniert. Details finden Sie unten.<br /><br />Auftragsnummer: %Order.OrderNumber%<br />Auftrags-Details: <a target="_blank" href="%Order.OrderURLForCustomer%">%Order.OrderURLForCustomer%</a><br />Auftrags-Datum: %Order.CreatedOn%<br /><br /><br /><br />Rechnungsadresse<br />%Order.BillingFirstName% %Order.BillingLastName%<br />%Order.BillingAddress1%<br />%Order.BillingCity% %Order.BillingZipPostalCode%<br />%Order.BillingStateProvince% %Order.BillingCountry%<br /><br /><br /><br />Lieferadresse<br />%Order.ShippingFirstName% %Order.ShippingLastName%<br />%Order.ShippingAddress1%<br />%Order.ShippingCity% %Order.ShippingZipPostalCode%<br />%Order.ShippingStateProvince% %Order.ShippingCountry%<br /><br />Versandart: %Order.ShippingMethod%<br /><br />%Order.Product(s)%</p> <p></p> <p>Mit freundlichen Gr&uuml;&szlig;en,</p> <p></p> <p>Ihr&nbsp;%Store.Name% - Team</p><br /><p>%Store.SupplierIdentification%</p></td></tr></tbody></table></center>'
	WHERE [Name] = 'OrderCancelled.CustomerNotification'
END
GO

IF EXISTS (SELECT 1 FROM [MessageTemplate] WHERE [Name] = 'OrderCompleted.CustomerNotification')
BEGIN
	UPDATE [MessageTemplate] SET [Body] = '<style type="text/css">address, blockquote, center, del, dir, div, dl, fieldset, form, h1, h2, h3, h4, h5, h6, hr, ins, isindex, menu, noframes, noscript, ol, p, pre, table{ margin:0px; } body, td, p{ font-size: 13px;font-family: ''Segoe UI'', Tahoma, Arial, Helvetica, sans-serif; line-height: 18px; color: #163764; } body{ background:#efefef; } p{ margin-top: 0px; margin-bottom: 10px; } img{ border:0px; } th{ font-weight:bold; color: #ffffff; padding: 5px 0 5px 0; } ul{ list-style-type: square; } li{ line-height: normal; margin-bottom: 5px; } .template-body { width:720px; padding: 10px; border: 1px solid #ccc; } .attr-caption { font-weight: bold; text-align:right; } .attr-value { text-align:right; min-width:158px; width:160px; } .legal-infos, .legal-infos p { font-size:11px; color: #aaa} .supplier-identification, .supplier-identification td { color: #646464; font-size: 11px } .supplier-identification { width:100%;border-top: 1px solid #ccc; border-bottom: 1px solid #ccc }</style><center><table border="0" cellpadding="0" cellspacing="0" align="center" bgcolor="#ffffff" class="template-body"><tbody><tr><td><p><a href="%Store.URL%">%Store.Name%</a>&nbsp;<br /><br />Hallo %Order.CustomerFullName%,&nbsp;</p> <p>Ihre Bestellung wurde bearbeitet.&nbsp;</p> <p></p> <p>Auftrags-Nummer: %Order.OrderNumber%<br />Details zum Auftrag:&nbsp;<a target="_blank" href="%Order.OrderURLForCustomer%">%Order.OrderURLForCustomer%</a><br />Datum: %Order.CreatedOn%<br /><br /><br /><br />Rechnungsadresse<br />%Order.BillingFirstName% %Order.BillingLastName%<br />%Order.BillingAddress1%<br />%Order.BillingCity% %Order.BillingZipPostalCode%<br />%Order.BillingStateProvince% %Order.BillingCountry%<br /><br /><br /><br />Lieferadresse<br />%Order.ShippingFirstName% %Order.ShippingLastName%<br />%Order.ShippingAddress1%<br />%Order.ShippingCity% %Order.ShippingZipPostalCode%<br />%Order.ShippingStateProvince% %Order.ShippingCountry%<br /><br />Versandart: %Order.ShippingMethod%<br />Zahlart: %Order.PaymentMethod%<br /><br />%Order.Product(s)%</p> <p></p> <p>Mit freundlichen Gr&uuml;&szlig;en,</p> <p></p> <p>Ihr&nbsp;%Store.Name% - Team</p><br /><p>%Store.SupplierIdentification%</p></td></tr></tbody></table></center>'
	WHERE [Name] = 'OrderCompleted.CustomerNotification'
END
GO

IF EXISTS (SELECT 1 FROM [MessageTemplate] WHERE [Name] = 'ShipmentDelivered.CustomerNotification')
BEGIN
	UPDATE [MessageTemplate] SET [Body] = '<style type="text/css">address, blockquote, center, del, dir, div, dl, fieldset, form, h1, h2, h3, h4, h5, h6, hr, ins, isindex, menu, noframes, noscript, ol, p, pre, table{ margin:0px; } body, td, p{ font-size: 13px;font-family: ''Segoe UI'', Tahoma, Arial, Helvetica, sans-serif; line-height: 18px; color: #163764; } body{ background:#efefef; } p{ margin-top: 0px; margin-bottom: 10px; } img{ border:0px; } th{ font-weight:bold; color: #ffffff; padding: 5px 0 5px 0; } ul{ list-style-type: square; } li{ line-height: normal; margin-bottom: 5px; } .template-body { width:720px; padding: 10px; border: 1px solid #ccc; } .attr-caption { font-weight: bold; text-align:right; } .attr-value { text-align:right; min-width:158px; width:160px; } .legal-infos, .legal-infos p { font-size:11px; color: #aaa} .supplier-identification, .supplier-identification td { color: #646464; font-size: 11px } .supplier-identification { width:100%;border-top: 1px solid #ccc; border-bottom: 1px solid #ccc }</style><center><table border="0" cellpadding="0" cellspacing="0" align="center" bgcolor="#ffffff" class="template-body"><tbody><tr><td><p><a href="%Store.URL%">%Store.Name%</a>&nbsp;<br /><br />Hallo %Order.CustomerFullName%,&nbsp;</p> <p>Ihre Bestellung wurde ausgeliefert.</p> <p>Auftrags-Nummer: %Order.OrderNumber%<br />Auftrags-Details:&nbsp;<a href="%Order.OrderURLForCustomer%" target="_blank">%Order.OrderURLForCustomer%</a><br />Datum: %Order.CreatedOn%<br /><br /><br /><br />Rechnungsadresse<br />%Order.BillingFirstName% %Order.BillingLastName%<br />%Order.BillingAddress1%<br />%Order.BillingCity% %Order.BillingZipPostalCode%<br />%Order.BillingStateProvince% %Order.BillingCountry%<br /><br /><br /><br />Lieferadresse<br />%Order.ShippingFirstName% %Order.ShippingLastName%<br />%Order.ShippingAddress1%<br />%Order.ShippingCity% %Order.ShippingZipPostalCode%<br />%Order.ShippingStateProvince% %Order.ShippingCountry%<br /><br />Versandart: %Order.ShippingMethod%&nbsp;<br />Zahlart: %Order.PaymentMethod%<br /><br />Gelieferte Artikel:&nbsp;<br /><br />%Shipment.Product(s)%</p><br /><p>%Store.SupplierIdentification%</p></td></tr></tbody></table></center>'
	WHERE [Name] = 'ShipmentDelivered.CustomerNotification'
END
GO

IF EXISTS (SELECT 1 FROM [MessageTemplate] WHERE [Name] = 'OrderPlaced.CustomerNotification')
BEGIN
	UPDATE [MessageTemplate] SET [Body] = '<style type="text/css">address, blockquote, center, del, dir, div, dl, fieldset, form, h1, h2, h3, h4, h5, h6, hr, ins, isindex, menu, noframes, noscript, ol, p, pre, table{ margin:0px; } body, td, p{ font-size: 13px;font-family: ''Segoe UI'', Tahoma, Arial, Helvetica, sans-serif; line-height: 18px; color: #163764; } body{ background:#efefef; } p{ margin-top: 0px; margin-bottom: 10px; } img{ border:0px; } th{ font-weight:bold; color: #ffffff; padding: 5px 0 5px 0; } ul{ list-style-type: square; } li{ line-height: normal; margin-bottom: 5px; } .template-body { width:720px; padding: 10px; border: 1px solid #ccc; } .attr-caption { font-weight: bold; text-align:right; } .attr-value { text-align:right; min-width:158px; width:160px; } .legal-infos, .legal-infos p { font-size:11px; color: #aaa} .supplier-identification, .supplier-identification td { color: #646464; font-size: 11px } .supplier-identification { width:100%;border-top: 1px solid #ccc; border-bottom: 1px solid #ccc }</style><center><table border="0" cellpadding="0" cellspacing="0" align="center" bgcolor="#ffffff" class="template-body"><tbody><tr><td><p><a href="%Store.URL%">%Store.Name%</a> <br /><br />Hallo %Order.CustomerFullName%, <br /> Vielen Dank f&uuml;r Ihre Bestellung bei <a href="%Store.URL%">%Store.Name%</a>. Eine &Uuml;bersicht &uuml;ber Ihre Bestellung finden Sie unten. <br /><br />Order Number: %Order.OrderNumber%<br /> Bestell&uuml;bersicht: <a target="_blank" href="%Order.OrderURLForCustomer%">%Order.OrderURLForCustomer%</a><br /> Datum: %Order.CreatedOn%<br /><br /><br /><br /> Rechnungsadresse<br />%Order.BillingFirstName% %Order.BillingLastName%<br />%Order.BillingAddress1%<br />%Order.BillingCity% %Order.BillingZipPostalCode%<br /> %Order.BillingStateProvince% %Order.BillingCountry%<br /><br /><br /><br /> Lieferadresse<br />%Order.ShippingFirstName% %Order.ShippingLastName%<br />%Order.ShippingAddress1%<br /> %Order.ShippingCity% %Order.ShippingZipPostalCode%<br />%Order.ShippingStateProvince% %Order.ShippingCountry%<br /><br /> Versandart: %Order.ShippingMethod%<br /> Zahlart: %Order.PaymentMethod%<br /><br />%Order.Product(s)%</p><br /><p>%Store.SupplierIdentification%</p><p>%Order.ConditionsOfUse%</p><p>%Order.Disclaimer%</p></td></tr></tbody></table></center>'
	WHERE [Name] = 'OrderPlaced.CustomerNotification'
END
GO

IF EXISTS (SELECT 1 FROM [MessageTemplate] WHERE [Name] = 'OrderPlaced.StoreOwnerNotification')
BEGIN
	UPDATE [MessageTemplate] SET [Body] = '<style type="text/css">address, blockquote, center, del, dir, div, dl, fieldset, form, h1, h2, h3, h4, h5, h6, hr, ins, isindex, menu, noframes, noscript, ol, p, pre, table{ margin:0px; } body, td, p{ font-size: 13px;font-family: ''Segoe UI'', Tahoma, Arial, Helvetica, sans-serif; line-height: 18px; color: #163764; } body{ background:#efefef; } p{ margin-top: 0px; margin-bottom: 10px; } img{ border:0px; } th{ font-weight:bold; color: #ffffff; padding: 5px 0 5px 0; } ul{ list-style-type: square; } li{ line-height: normal; margin-bottom: 5px; } .template-body { width:720px; padding: 10px; border: 1px solid #ccc; } .attr-caption { font-weight: bold; text-align:right; } .attr-value { text-align:right; min-width:158px; width:160px; } .legal-infos, .legal-infos p { font-size:11px; color: #aaa} .supplier-identification, .supplier-identification td { color: #646464; font-size: 11px } .supplier-identification { width:100%;border-top: 1px solid #ccc; border-bottom: 1px solid #ccc }</style><center><table border="0" cellpadding="0" cellspacing="0" align="center" bgcolor="#ffffff" class="template-body"><tbody><tr><td><p><a href="%Store.URL%">%Store.Name%</a>&nbsp;</p> <p></p> <p>Eine neue Bestellung wurde get&auml;tigt:</p> <p><br />Kunden: %Order.CustomerFullName% (%Order.CustomerEmail%) .&nbsp;<br /><br />Auftrags-Nummer: %Order.OrderNumber%<br />Datum: %Order.CreatedOn%<br /><br /><br /><br />Rechnungsadresse<br />%Order.BillingFirstName% %Order.BillingLastName%<br />%Order.BillingAddress1%<br />%Order.BillingCity% %Order.BillingZipPostalCode%<br />%Order.BillingStateProvince% %Order.BillingCountry%<br /><br /><br /><br />Lieferadresse<br />%Order.ShippingFirstName% %Order.ShippingLastName%<br />%Order.ShippingAddress1%<br />%Order.ShippingCity% %Order.ShippingZipPostalCode%<br />%Order.ShippingStateProvince% %Order.ShippingCountry%<br /><br />Versandart: %Order.ShippingMethod% <br /> Zahlart: %Order.PaymentMethod%<br /><br />%Order.Product(s)%</p></td></tr></tbody></table></center>'
	WHERE [Name] = 'OrderPlaced.StoreOwnerNotification'
END
GO

IF EXISTS (SELECT 1 FROM [MessageTemplate] WHERE [Name] = 'ShipmentSent.CustomerNotification')
BEGIN
	UPDATE [MessageTemplate] SET [Body] = '<style type="text/css">address, blockquote, center, del, dir, div, dl, fieldset, form, h1, h2, h3, h4, h5, h6, hr, ins, isindex, menu, noframes, noscript, ol, p, pre, table{ margin:0px; } body, td, p{ font-size: 13px;font-family: ''Segoe UI'', Tahoma, Arial, Helvetica, sans-serif; line-height: 18px; color: #163764; } body{ background:#efefef; } p{ margin-top: 0px; margin-bottom: 10px; } img{ border:0px; } th{ font-weight:bold; color: #ffffff; padding: 5px 0 5px 0; } ul{ list-style-type: square; } li{ line-height: normal; margin-bottom: 5px; } .template-body { width:720px; padding: 10px; border: 1px solid #ccc; } .attr-caption { font-weight: bold; text-align:right; } .attr-value { text-align:right; min-width:158px; width:160px; } .legal-infos, .legal-infos p { font-size:11px; color: #aaa} .supplier-identification, .supplier-identification td { color: #646464; font-size: 11px } .supplier-identification { width:100%;border-top: 1px solid #ccc; border-bottom: 1px solid #ccc }</style><center><table border="0" cellpadding="0" cellspacing="0" align="center" bgcolor="#ffffff" class="template-body"><tbody><tr><td><p><a href="%Store.URL%">%Store.Name%</a>&nbsp;<br /><br />Hallo %Order.CustomerFullName%,&nbsp;</p> <p><br />Ihre Bestellung wurde soeben versendet:</p> <p><br />Auftrags-Nummer: %Order.OrderNumber%<br />Auftrags-Details:&nbsp;<a href="%Order.OrderURLForCustomer%" target="_blank">%Order.OrderURLForCustomer%</a><br />Datum: %Order.CreatedOn%<br /><br /><br />Rechnungsadresse<br />%Order.BillingFirstName% %Order.BillingLastName%<br />%Order.BillingAddress1%<br />%Order.BillingCity% %Order.BillingZipPostalCode%<br />%Order.BillingStateProvince% %Order.BillingCountry%<br /><br /><br /><br />Lieferadresse<br />%Order.ShippingFirstName% %Order.ShippingLastName%<br />%Order.ShippingAddress1%<br />%Order.ShippingCity% %Order.ShippingZipPostalCode%<br />%Order.ShippingStateProvince% %Order.ShippingCountry%<br /><br />Versandart: %Order.ShippingMethod%&nbsp;<br />Zahlart: %Order.PaymentMethod%<br /><br />Versendete Artikel:&nbsp;<br /><br />%Shipment.Product(s)%</p><br /><p>%Store.SupplierIdentification%</p></td></tr></tbody></table></center>'
	WHERE [Name] = 'ShipmentSent.CustomerNotification'
END
GO

IF EXISTS (SELECT 1 FROM [MessageTemplate] WHERE [Name] = 'Product.ProductReview')
BEGIN
	UPDATE [MessageTemplate] SET [Body] = '<style type="text/css">address, blockquote, center, del, dir, div, dl, fieldset, form, h1, h2, h3, h4, h5, h6, hr, ins, isindex, menu, noframes, noscript, ol, p, pre, table{ margin:0px; } body, td, p{ font-size: 13px;font-family: ''Segoe UI'', Tahoma, Arial, Helvetica, sans-serif; line-height: 18px; color: #163764; } body{ background:#efefef; } p{ margin-top: 0px; margin-bottom: 10px; } img{ border:0px; } th{ font-weight:bold; color: #ffffff; padding: 5px 0 5px 0; } ul{ list-style-type: square; } li{ line-height: normal; margin-bottom: 5px; } .template-body { width:720px; padding: 10px; border: 1px solid #ccc; } .attr-caption { font-weight: bold; text-align:right; } .attr-value { text-align:right; min-width:158px; width:160px; } .legal-infos, .legal-infos p { font-size:11px; color: #aaa} .supplier-identification, .supplier-identification td { color: #646464; font-size: 11px } .supplier-identification { width:100%;border-top: 1px solid #ccc; border-bottom: 1px solid #ccc }</style><center><table border="0" cellpadding="0" cellspacing="0" align="center" bgcolor="#ffffff" class="template-body"><tbody><tr><td><p><a href="%Store.URL%">%Store.Name%</a>&nbsp;</p> <p>Eine neue Produktrezension zu dem Produkt&nbsp;"%ProductReview.ProductName%" wurde verfasst.<br /><br /></p></td></tr></tbody></table></center>'
	WHERE [Name] = 'Product.ProductReview'
END
GO


IF EXISTS (SELECT 1 FROM [MessageTemplate] WHERE [Name] = 'QuantityBelow.StoreOwnerNotification')
BEGIN
	UPDATE [MessageTemplate] SET [Body] = '<style type="text/css">address, blockquote, center, del, dir, div, dl, fieldset, form, h1, h2, h3, h4, h5, h6, hr, ins, isindex, menu, noframes, noscript, ol, p, pre, table{ margin:0px; } body, td, p{ font-size: 13px;font-family: ''Segoe UI'', Tahoma, Arial, Helvetica, sans-serif; line-height: 18px; color: #163764; } body{ background:#efefef; } p{ margin-top: 0px; margin-bottom: 10px; } img{ border:0px; } th{ font-weight:bold; color: #ffffff; padding: 5px 0 5px 0; } ul{ list-style-type: square; } li{ line-height: normal; margin-bottom: 5px; } .template-body { width:720px; padding: 10px; border: 1px solid #ccc; } .attr-caption { font-weight: bold; text-align:right; } .attr-value { text-align:right; min-width:158px; width:160px; } .legal-infos, .legal-infos p { font-size:11px; color: #aaa} .supplier-identification, .supplier-identification td { color: #646464; font-size: 11px } .supplier-identification { width:100%;border-top: 1px solid #ccc; border-bottom: 1px solid #ccc }</style><center><table border="0" cellpadding="0" cellspacing="0" align="center" bgcolor="#ffffff" class="template-body"><tbody><tr><td><p><a href="%Store.URL%">%Store.Name%</a>&nbsp;</p> <p>Der Mindestlagerbestand f&uuml;r folgendes produkt wurde unterschritte;<br />%ProductVariant.FullProductName% (ID: %ProductVariant.ID%) &nbsp;<br /><br />Menge: %ProductVariant.StockQuantity%</p></td></tr></tbody></table></center>'
	WHERE [Name] = 'QuantityBelow.StoreOwnerNotification'
END
GO

IF EXISTS (SELECT 1 FROM [MessageTemplate] WHERE [Name] = 'ReturnRequestStatusChanged.CustomerNotification')
BEGIN
	UPDATE [MessageTemplate] SET [Body] = '<style type="text/css">address, blockquote, center, del, dir, div, dl, fieldset, form, h1, h2, h3, h4, h5, h6, hr, ins, isindex, menu, noframes, noscript, ol, p, pre, table{ margin:0px; } body, td, p{ font-size: 13px;font-family: ''Segoe UI'', Tahoma, Arial, Helvetica, sans-serif; line-height: 18px; color: #163764; } body{ background:#efefef; } p{ margin-top: 0px; margin-bottom: 10px; } img{ border:0px; } th{ font-weight:bold; color: #ffffff; padding: 5px 0 5px 0; } ul{ list-style-type: square; } li{ line-height: normal; margin-bottom: 5px; } .template-body { width:720px; padding: 10px; border: 1px solid #ccc; } .attr-caption { font-weight: bold; text-align:right; } .attr-value { text-align:right; min-width:158px; width:160px; } .legal-infos, .legal-infos p { font-size:11px; color: #aaa} .supplier-identification, .supplier-identification td { color: #646464; font-size: 11px } .supplier-identification { width:100%;border-top: 1px solid #ccc; border-bottom: 1px solid #ccc }</style><center><table border="0" cellpadding="0" cellspacing="0" align="center" bgcolor="#ffffff" class="template-body"><tbody><tr><td><p><a href="%Store.URL%">%Store.Name%</a>&nbsp;<br /><br />Hallo %Customer.FullName%,</p> <p>der Status Ihrer R&uuml;cksendung&nbsp;#%ReturnRequest.ID% wurde aktualisiert.</p> <p></p> <p>Mit freundlichen Gr&uuml;&szlig;en,</p> <p></p> <p>Ihr&nbsp;%Store.Name% - Team</p></td></tr></tbody></table></center>'
	WHERE [Name] = 'ReturnRequestStatusChanged.CustomerNotification'
END
GO

IF EXISTS (SELECT 1 FROM [MessageTemplate] WHERE [Name] = 'Service.EmailAFriend')
BEGIN
	UPDATE [MessageTemplate] SET [Body] = '<style type="text/css">address, blockquote, center, del, dir, div, dl, fieldset, form, h1, h2, h3, h4, h5, h6, hr, ins, isindex, menu, noframes, noscript, ol, p, pre, table{ margin:0px; } body, td, p{ font-size: 13px;font-family: ''Segoe UI'', Tahoma, Arial, Helvetica, sans-serif; line-height: 18px; color: #163764; } body{ background:#efefef; } p{ margin-top: 0px; margin-bottom: 10px; } img{ border:0px; } th{ font-weight:bold; color: #ffffff; padding: 5px 0 5px 0; } ul{ list-style-type: square; } li{ line-height: normal; margin-bottom: 5px; } .template-body { width:720px; padding: 10px; border: 1px solid #ccc; } .attr-caption { font-weight: bold; text-align:right; } .attr-value { text-align:right; min-width:158px; width:160px; } .legal-infos, .legal-infos p { font-size:11px; color: #aaa} .supplier-identification, .supplier-identification td { color: #646464; font-size: 11px } .supplier-identification { width:100%;border-top: 1px solid #ccc; border-bottom: 1px solid #ccc }</style><center><table border="0" cellpadding="0" cellspacing="0" align="center" bgcolor="#ffffff" class="template-body"><tbody><tr><td><p><a href="%Store.URL%">%Store.Name%</a>&nbsp;<br /><br />%EmailAFriend.Email% m&ouml;chte Ihnen bei %Store.Name% ein Produkt empfehlen:<br /><br /><b><a target="_blank" href="%Product.ProductURLForCustomer%">%Product.Name%</a></b>&nbsp;<br />%Product.ShortDescription%&nbsp;</p> <p></p> <p>Weitere Details finden Sie <a target="_blank" href="%Product.ProductURLForCustomer%">hier</a><br /><br /><br />%EmailAFriend.PersonalMessage%</p> <p></p> <p>Mit freundlichen Gr&uuml;&szlig;en,</p> <p><br />Ihr %Store.Name% - Team</p></td></tr></tbody></table></center>'
	WHERE [Name] = 'Service.EmailAFriend'
END
GO

IF EXISTS (SELECT 1 FROM [MessageTemplate] WHERE [Name] = 'Wishlist.EmailAFriend')
BEGIN
	UPDATE [MessageTemplate] SET [Body] = '<style type="text/css">address, blockquote, center, del, dir, div, dl, fieldset, form, h1, h2, h3, h4, h5, h6, hr, ins, isindex, menu, noframes, noscript, ol, p, pre, table{ margin:0px; } body, td, p{ font-size: 13px;font-family: ''Segoe UI'', Tahoma, Arial, Helvetica, sans-serif; line-height: 18px; color: #163764; } body{ background:#efefef; } p{ margin-top: 0px; margin-bottom: 10px; } img{ border:0px; } th{ font-weight:bold; color: #ffffff; padding: 5px 0 5px 0; } ul{ list-style-type: square; } li{ line-height: normal; margin-bottom: 5px; } .template-body { width:720px; padding: 10px; border: 1px solid #ccc; } .attr-caption { font-weight: bold; text-align:right; } .attr-value { text-align:right; min-width:158px; width:160px; } .legal-infos, .legal-infos p { font-size:11px; color: #aaa} .supplier-identification, .supplier-identification td { color: #646464; font-size: 11px } .supplier-identification { width:100%;border-top: 1px solid #ccc; border-bottom: 1px solid #ccc }</style><center><table border="0" cellpadding="0" cellspacing="0" align="center" bgcolor="#ffffff" class="template-body"><tbody><tr><td><p><a href="%Store.URL%">%Store.Name%</a>&nbsp;<br /><br />%Wishlist.Email% m&ouml;chte mit Ihnen ihre/seine Wunschliste teilen.<br /><br /></p> <p>Um die Wunschliste einzusehen, klicken Sie bitte <a target="_blank" href="%Wishlist.URLForCustomer%">hier</a>.<br /><br /><br /></p> <p>%Wishlist.PersonalMessage%<br /><br />%Store.Name%</p></td></tr></tbody></table></center>'
	WHERE [Name] = 'Wishlist.EmailAFriend'
END
GO

IF EXISTS (SELECT 1 FROM [MessageTemplate] WHERE [Name] = 'Customer.NewOrderNote')
BEGIN
	UPDATE [MessageTemplate] SET [Body] = '<style type="text/css">address, blockquote, center, del, dir, div, dl, fieldset, form, h1, h2, h3, h4, h5, h6, hr, ins, isindex, menu, noframes, noscript, ol, p, pre, table{ margin:0px; } body, td, p{ font-size: 13px;font-family: ''Segoe UI'', Tahoma, Arial, Helvetica, sans-serif; line-height: 18px; color: #163764; } body{ background:#efefef; } p{ margin-top: 0px; margin-bottom: 10px; } img{ border:0px; } th{ font-weight:bold; color: #ffffff; padding: 5px 0 5px 0; } ul{ list-style-type: square; } li{ line-height: normal; margin-bottom: 5px; } .template-body { width:720px; padding: 10px; border: 1px solid #ccc; } .attr-caption { font-weight: bold; text-align:right; } .attr-value { text-align:right; min-width:158px; width:160px; } .legal-infos, .legal-infos p { font-size:11px; color: #aaa} .supplier-identification, .supplier-identification td { color: #646464; font-size: 11px } .supplier-identification { width:100%;border-top: 1px solid #ccc; border-bottom: 1px solid #ccc }</style><center><table border="0" cellpadding="0" cellspacing="0" align="center" bgcolor="#ffffff" class="template-body"><tbody><tr><td><p><a href="%Store.URL%">%Store.Name%</a>&nbsp;</p> <p></p> <p>Hallo&nbsp;%Customer.FullName%,&nbsp;</p> <p></p> <p>Ihrem Auftrag wurde eine Notiz hinterlegt:</p> <p>"%Order.NewNoteText%".<br /><a target="_blank" href="%Order.OrderURLForCustomer%">%Order.OrderURLForCustomer%</a></p> <p></p> <p>Mit freundlichen Gr&uuml;&szlig;en,</p> <p></p> <p>Ihr Shop-Team</p></td></tr></tbody></table></center>'
	WHERE [Name] = 'Customer.NewOrderNote'
END
GO

IF EXISTS (SELECT 1 FROM [MessageTemplate] WHERE [Name] = 'RecurringPaymentCancelled.StoreOwnerNotification')
BEGIN
	UPDATE [MessageTemplate] SET [Body] = '<style type="text/css">address, blockquote, center, del, dir, div, dl, fieldset, form, h1, h2, h3, h4, h5, h6, hr, ins, isindex, menu, noframes, noscript, ol, p, pre, table{ margin:0px; } body, td, p{ font-size: 13px;font-family: ''Segoe UI'', Tahoma, Arial, Helvetica, sans-serif; line-height: 18px; color: #163764; } body{ background:#efefef; } p{ margin-top: 0px; margin-bottom: 10px; } img{ border:0px; } th{ font-weight:bold; color: #ffffff; padding: 5px 0 5px 0; } ul{ list-style-type: square; } li{ line-height: normal; margin-bottom: 5px; } .template-body { width:720px; padding: 10px; border: 1px solid #ccc; } .attr-caption { font-weight: bold; text-align:right; } .attr-value { text-align:right; min-width:158px; width:160px; } .legal-infos, .legal-infos p { font-size:11px; color: #aaa} .supplier-identification, .supplier-identification td { color: #646464; font-size: 11px } .supplier-identification { width:100%;border-top: 1px solid #ccc; border-bottom: 1px solid #ccc }</style><center><table border="0" cellpadding="0" cellspacing="0" align="center" bgcolor="#ffffff" class="template-body"><tbody><tr><td><p><a href="%Store.URL%">%Store.Name%</a>&nbsp;</p> <p>Folgende wiederkehrende Zahlung wurde vom Kunden storniert:</p> <p>Zahlungs-ID=%RecurringPayment.ID%<br />Kunden-Name und E-Mail: %Customer.FullName% (%Customer.Email%)&nbsp;</p></td></tr></tbody></table></center>'
	WHERE [Name] = 'RecurringPaymentCancelled.StoreOwnerNotification'
END
GO

